# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
setopt autocd
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/rajs/.zshrc'
export EDITOR='nvim'
export VISUAL='nvim'
autoload -Uz compinit
compinit
compdef '_normal doas command' doas
export PATH=/home/ragef/.cargo/bin:$PATH
export PATH=/home/ragef/.local/bin:$PATH
export PATH=$PATH:$HOME/go/bin
export GPG_TTY=$(tty)
alias sudo="doasidisahdiluahwdoliuakjwshdfiopawufhaespofihjewd"
alias "yay"="paru"
alias ncdu="ncdu --exclude-kernfs"
if [ ! -z "$PS1" ]; then
	for util in $(coreutils --list); do
		alias "$util"="coreutils $util"
	done
fi
setopt interactivecomments
eval `ssh-agent` > /dev/null 2>&1
fastfetch
eval "$(starship init zsh)"
