format = """ 
$username\
$directory\
$aws\
$buf\
$c\
$cmake\
$conda\
$crystal\
$dart\
$docker_context\
$elixir\
$elm\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$hg_branch\
$hostname\
$java\
$julia\
$kotlin\
$memory_usage\
$meson\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$zig\
$gradle\
$git_branch\
$git_commit\
$git_status
$os \
$character
"""
add_newline = false
[username]
show_always = true
format = '[$user ](fg:blue)'
disabled = false

[os]
disabled = false
style = 'fg:blue'
[os.symbols]
Alpine = " "
Arch = " "
Artix = " "
CachyOS = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Linux = " "
NixOS = " "
openSUSE = " "
Solus = "󰠳 "
Void = " "
[cmd_duration]
format = "[$duration](fg:purple)"

[directory]
format = "[$path](fg:purple)"
truncation_length = 6
truncation_symbol = "…/"

[character]
success_symbol = "[](bold blue)"
error_symbol = "[✗](bold purple)"
disabled = false

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = "󰝚 "
"pictures" = " "
"scripts" = "󰲋 "
".local/bin" = "󰲋 "

[fossil_branch]
symbol = "  "
format = '[$symbol($version)]($style)'

[git_branch]
symbol = "  "
format = '[$symbol($branch) ($version)]($style)'
ignore_branches = ['master', 'main']

[git_commit]
tag_symbol = '  '
format = '[$symbol($version)]($style)'
[git_status]
deleted = '✗'
format = '[ $all_status $ahead_behind]($style)'
[aws]
symbol = "   "
format = '[$symbol]($style)'

[buf]
symbol = "  "
format = '[$symbol]($style)'

[c]
symbol = "  "
format = '[$symbol]($style)'

[cmake]
symbol = "  "
format = '[$symbol]($style)'

[conda]
symbol = "  "
format = '[$symbol]($style)'

[crystal]
symbol = "  "
format = '[$symbol]($style)'

[dart]
symbol = "  "
format = '[$symbol]($style)'

[docker_context]
symbol = "  "
format = '[$symbol]($style)'

[elixir]
symbol = "  "
format = '[$symbol]($style)'

[elm]
symbol = "  "
format = '[$symbol]($style)'

[fennel]
symbol = "  "
format = '[$symbol]($style)'

[golang]
symbol = "  "
format = '[$symbol]($style)'

[guix_shell]
symbol = "   "
format = '[$symbol]($style)'

[haskell]
symbol = "  "
format = '[$symbol]($style)'

[haxe]
symbol = "  "
format = '[$symbol]($style)'

[hg_branch]
symbol = "  "
format = '[$symbol]($style)'

[hostname]
ssh_symbol = "  "
format = '[$symbol]($style)'

[java]
symbol = "  "
format = '[$symbol]($style)'

[julia]
symbol = "  "
format = '[$symbol]($style)'

[kotlin]
symbol = "  "
format = '[$symbol]($style)'

[lua]
symbol = "  "
format = '[$symbol]($style)'

[memory_usage]
symbol = " 󰍛 "
format = '[$symbol]($style)'

[meson]
symbol = " 󰔷 "
format = '[$symbol]($style)'

[nim]
symbol = " 󰆥 "
format = '[$symbol]($style)'

[nix_shell]
symbol = "  "
format = '[$symbol]($style)'

[nodejs]
symbol = "  "
format = '[$symbol]($style)'

[ocaml]
symbol = "  "
format = '[$symbol]($style)'

[package]
symbol = " 󰏗 "
format = '[$symbol]($style)'

[perl]
symbol = "  "
format = '[$symbol]($style)'

[php]
symbol = "  "
format = '[$symbol]($style)'

[pijul_channel]
symbol = "  "
format = '[$symbol]($style)'

[python]
symbol = "  "
format = '[$symbol]($style)'

[rlang]
symbol = " 󰟔 "
format = '[$symbol]($style)'

[ruby]
symbol = "  "
format = '[$symbol]($style)'

[rust]
symbol = " 󱘗 "
format = '[$symbol]($style)'

[scala]
symbol = "  "
format = '[$symbol]($style)'

[swift]
symbol = "  "
format = '[$symbol]($style)'

[zig]
symbol = "  "
format = '[$symbol]($style)'

[gradle]
symbol = "  "
format = '[$symbol]($style)'
