[helpers]

[default]
depends = []

[default.files]

# Rcs/profile

"rc/profile" = "~/.profile"

# Decoration

"decor/fastfetch" = "~/.config/fastfetch"
"decor/hypr" = "~/.config/hypr"
"decor/starship.toml" = "~/.config/starship.toml"
"wallpaper" = { target = "~/.wallpaper", type = "symbolic" }
"decor/wallust/templates" = { target = "~/.config/wallust/templates", type = "symbolic" }
"decor/wallust/wallust.toml" = "~/.config/wallust/wallust.toml"
"decor/quickshell" = "~/.config/quickshell"
# Functional Utilities

# "utils/alacritty" = "~/.config/alacritty"
"utils/kanata" = "~/.config/kanata"
# "utils/kitty" = "~/.config/kitty"
# "utils/lf" = "~/.config/lf"
"utils/btop" = "~/.config/btop"
# "utils/makepkg.conf" = "~/makepkg.conf"
# "utils/tmux.conf" = "~/.tmux.conf"
# "utils/paru" = "~/.config/paru"
"utils/wofi" = "~/.config/wofi"
"utils/wezterm" = "~/.config/wezterm"
"utils/helix" = "~/.config/helix"
# "utils/greetd" = { target = "/etc/greetd", owner = "root", type = "template" }
"utils/nushell" = "~/.config/nushell"
"utils/niri" = "~/.config/niri"
# "utils/swaylock" = "~/.config/swaylock/config"
"utils/waypaper/style.css" = "~/.config/waypaper/style.css"
"scripts" = "~/.scripts"
[default.variables]
font = "JetBrainsMono Nerd Font"
fsize = 13
lfsize = 20
opacity = 0.95
terminal = 'wezterm'
[settings]
default_target_type = "automatic"
